============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/runner/work/flask/flask
configfile: pyproject.toml
plugins: cov-5.0.0
collected 0 items
WARNING: Failed to generate report: No data to report.



---------- coverage: platform linux, python 3.8.18-final-0 -----------

============================ no tests ran in 0.03s =============================
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/runner/work/flask/flask
configfile: pyproject.toml
plugins: cov-5.0.0
collected 0 items / 1 error
WARNING: Failed to generate report: No data to report.


==================================== ERRORS ====================================
_____________ ERROR collecting generated_tests/python/test_app.py ______________
ImportError while importing test module '/home/runner/work/flask/flask/generated_tests/python/test_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
generated_tests/python/test_app.py:7: in <module>
    from flask import Flask, template_rendered
E   ModuleNotFoundError: No module named 'flask'

---------- coverage: platform linux, python 3.8.18-final-0 -----------

=========================== short test summary info ============================
ERROR generated_tests/python/test_app.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.19s ===============================
